[package]
name = "unogame"
authors = ["Ankit Agrawal <ankitagrawal620@gmail.com>"]
version = "0.1.0"
edition = "2023_11"
cairo = "2.8.5"


# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.5"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.27.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"

[tool.snforge]
exit_first = true
